### ISSUE TITLE
name: Build action on: [pull_request]  jobs:   Build:     runs-on: macos-latest     steps:     - name: Checkout       uses: actions/checkout@master      - name: Set Node.JS       uses: actions/setup-node@master       with:         node-version: 12.x      - name: npm install       run: npm install      - name: Build       run: npm run build

### ISSUE THREAD

**Issue by williamhannry** [al-cheb/configure-pagefile-action#12]

**Comment by mikehardy** [comment]
this issue is a bit incoherent sorry
I can say this: the action not be run on macos runners, it will throw an exception and fail your build on anything but windows

Try this, for instance, if you are using a multi-operating system build matrix

```yaml

      - name: Configure Windows Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
        if: matrix.os == 'windows-latest'
        with:
          minimum-size: 8GB
          maximum-size: 12GB
          disk-root: "D:"
```
